### ISSUE TITLE
AOS causing horizontal scroll bar to appear

### ISSUE THREAD

**Issue by nom3d** [michalsnik/aos#416]
## This is:

- Bug
- Feature request
- Question
- Idea

## Specifications

  - AOS version:2.3.4
  - OS:win7
  - Browser:firefox

## Expected Behavior
No horizontal scrollbar

## Actual Behavior
AOS causing horizontal scroll bar to appear when browser window is sized under 1000px or so.. seems to happen on the data-aos="fade-right" and data-aos="fade-left". When the container is say 800px wide and the browser is around 850-900 a horizontal scrollbar will appear until you scroll down and the effect is done.

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by sGentiletti** [comment]
overflow: hidden; for that container, and we can wait for the fix.

**Comment by BuRTaRT** [comment]
Yep,the same problem.

**Comment by jbator** [comment]
Same issue here. Usning bootstrap4 ".container-fluid" and rows with data-aos="fade-right" and data-aos="fade-left".

**Comment by aronmeszaros** [comment]
> overflow: hidden; for that container, and we can wait for the fix.

or perhaps because fade-right and fade-left is the case, overflow-x: hidden;  would be the best

**Comment by tomihbk** [comment]
Same problem.

**Comment by mzvarik** [comment]
This will never be fixed... this library should be erased and not used.

**Comment by antonyleme** [comment]
Not solved yet. I can't use overflow-x: hidden because the navbar goes out beyond the page

**Comment by jonasmarco** [comment]
Sadly, same problem here.
I'd to use overflow-x:hidden on mobile to solve it.

**Comment by nicolaskeller** [comment]
overflow-x: hidden; on the body fixed it for me.

**Comment by CaioSilvaWeb** [comment]
I used overflow-x: hidden in the mother div and solved the problem, excellent library.

**Comment by siemlohuis** [comment]
Same for me on any size with `text-align: center;`

**Comment by juliebam** [comment]
I have this issue but only chrome and mobile. overflow-x:hidden doesn't seem to fix it. (its fine on firefox)

**Comment by Ariansdf** [comment]
> overflow-x: hidden; on the body fixed it for me.

SAME HERE ! thanks ! that was a life saver !!!
my div position is absolute, so it seems that the parent div overflow:hidden would not work ! (maybe ! not sure really why)

**Comment by AliHussain85** [comment]
And what about the shadow of elements that get's hide due to overflow:hidden of parent div?
![Ca6pture](https://user-images.githubusercontent.com/42221390/75292877-e4ee5100-5846-11ea-8628-ec523d533022.PNG)

**Comment by SaeedEsk** [comment]
header,
section {
  width: 100%;
  float: left;
  overflow: hidden;
}

**Comment by Ateyyah-Buthor** [comment]
Well, for me the overflow: hidden thing worked only on desktop view..
but on mobile, I fixed it with something similar...
My whole HTML body is divided into sections..

That's what I put in my CSS file -=And worked fine on mobile=- :
section {
 overflow:hidden;
}

**Comment by volkandkaya** [comment]
Body never worked, using overflow hidden on section was perfect.

**Comment by Dulanka-K** [comment]
overflow-x: hidden; in body alone didn't fix. Had to include following meta tag too

meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no"

**Comment by edunwa302** [comment]
> overflow-x: hidden; on the body fixed it for me.

this works for you ...thanks

**Comment by edunwa302** [comment]
> I used overflow-x: hidden in the mother div and solved the problem, excellent library.

works for me

**Comment by 766kadir** [comment]
Firstly ı'm so sory for my bad lang. I've same problem. "overflow-x in aos". I many tried but ı finally find. I set css html, body max-width : 99%.  In this way works it. Only loss %1 width. İf u dont worry for this, maybe u can use.

**Comment by MetalxD117** [comment]
> overflow-x: hidden; in body alone didn't fix. Had to include following meta tag too
> 
> meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no"

This absolutely works for my problem, thanks bro!!!!

**Comment by ramapermadoni** [comment]
> overflow: hidden; for that container, and we can wait for the fix.

thank you very much, it works

**Comment by Air-Sidney** [comment]
Or you can begin animation from another side xD

**Comment by San-tiago** [comment]
> overflow-x: hidden; in body alone didn't fix. Had to include following meta tag too
> 
> meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no"

this works for me, thanks buddy

**Comment by Nwoye-Ezekiel** [comment]
> overflow-x: hidden; in body alone didn't fix. Had to include following meta tag too
> 
> meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no"

Thank you so much! it worked.

**Comment by pkaustubh401** [comment]
> overflow-x: hidden; in body alone didn't fix. Had to include following meta tag too
> 
> meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no"

This totally worked for me , only using overflow-x:hidden hides some elements of navbar so use the meta tag for complete working

**Comment by Hydrodamalis** [comment]
For this to work, add overflow: hidden to html.

html, body{
overflow: hidden}

**Comment by nooroffical** [comment]
.container {
    overflow: hidden;
}
add css only "container", not html or body.
worked for me.

**Comment by snowiewdev** [comment]
i'm using vue with php, each page has a div with id=app, the following works for me:

body, #app {
  overflow-x: hidden;
}

I guess it just needs to add a overflow-hidden class to a container that wraps around the elements with aos applied 
hope this helps

**Comment by jessedmatlock** [comment]
Unfortunate that this isn't resolved, still.
I tried the meta name tag, no dice..
but, overflow-x: hidden on html and body resolved it. I've using a media query to only implement for mobile screens.

`@media (max-width: 992px) {
  html,
  body {
    overflow-x: hidden !important;
    overflow-y: visible !important;
  }
}
`

**Comment by mRahulRoy** [comment]
> Not solved yet. I can't use overflow-x: hidden because the navbar goes out beyond the page

use overflow-x : hidden and this will solve your problem

**Comment by mRahulRoy** [comment]
use overflow-x : hidden and this will solve your problem

**Comment by syedahmedrz** [comment]
> 

Perfect solution for that... recommended

**Comment by Farhan100X** [comment]
[766kadir](https://github.com/766kadir)

> Firstly ı'm so sory for my bad lang. I've same problem. "overflow-x in aos". I many tried but ı finally find. I set css html, body max-width : 99%. In this way works it. Only loss %1 width. İf u dont worry for this, maybe u can use.

Make it 99.9%. It solves the problem of AOS + you won't see any decrease in width.  [766kadir](https://github.com/766kadir) Thanx

**Comment by romulis** [comment]
Overflow: hidden is great... unless you want to incorporate a css sticky element or have an element overlap another element, then not so great.  overflow-x: clip works better than hidden and is compatible with css sticky element.

**Comment by Mos3aB696** [comment]
To Solve This Don't Use ( flip-up | flip-down | zoom out ) And Another Values Going Greate

**Comment by MozerBuce** [comment]
I got the same problem using slide and i tried to change many things on the layout and nothing, for now i using this:
`overflow-x: hidden; `

**Comment by issam-seghir** [comment]
`overflow-x: hidden; `
 for the parent `div ` fix the problem

**Comment by tutods** [comment]
For me the meta tag doesn't work.

**Comment by matildasmets** [comment]
Same issue here. Tried applying it to the body, no changes, to HTML & BODY, just made it literally impossible to scroll down on smaller devices, I literally could not scroll down. If I could, the AOS animations wouldn't play. It's terrible that this issue has been around since 2018! That's crazy.. even applying it to the containers didn't help, couldn't scroll down on smaller devices.

**Comment by shreygargofficial** [comment]
Hey Guys!!! I have fixed the issue for me just replaced `zoom-out` with `zoom-in` as zoom-out initially takes the space more than the parent container hope this would help

**Comment by fabiviegas** [comment]
> I used overflow-x: hidden in the mother div and solved the problem, excellent library.

thanks bro!

**Comment by tutods** [comment]
Anyone having issues on Next.js?
Like: `Warning: Prop `className` did not match. Server: "text-4xl font-bold tracking-tight text-white sm:text-6xl aos-init aos-animate" Client: "text-4xl font-bold tracking-tight text-white sm:text-6xl"`

**Comment by V4LKYR13101** [comment]
> overflow-x: hidden; in body alone didn't fix. Had to include following meta tag too
> 
> meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no"

This is the full answer. overflow-x: hidden and the additional viewport section. Thank you Dulanka-K

**Comment by elielson-and** [comment]
✅Solved.

im using tailwind, so i just passed overflow-x-hidden on the main component (entire app), however if it doesn't work for your case.  you can try adding it to the body instead of the main component. Additionaly to force it you can try: !important:

css: overflow: hidden !important;

**Comment by Sivayogeith** [comment]
> overflow: hidden;

needed this, and the workaround works amazingly! i was about to give up lol.

**Comment by webdev69420** [comment]
If it can help: I just fixed this by using overflow-x: clip; instead. [Browser support](https://caniuse.com/?search=overflow-x%3A%20clip%3B) is enough for my needs but check before using it on your project I guess. Seems to be working just fine for me!

**Comment by wanghuaimin2024** [comment]
Thank you for the experience shared above. After adding overflow:hidden to the parent element of the component, the width overflow issue was resolved.
